[package]
name = "flagserver"
version = "0.1.0"
authors = ["Michael Eden <themichaeleden@gmail.com>"]

[dependencies]
csv = "*"
rustc-serialize = "*"
wire = "*"

[dependencies.ctfcommon]
path = "../ctfcommon"

[dependencies.firebase]
git = "https://github.com/davidrhyswhite/rust-firebase"
